# Generated by Django 4.2 on 2023-04-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("borrowing", "0017_alter_borrowing_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Hard"), ("PAID", "Soft")], max_length=63
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "Hard"), ("FINE", "Soft")], max_length=63
                    ),
                ),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=50)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
