# Generated by Django 4.2 on 2023-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid")], max_length=63
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("FINE", "Fine")], max_length=63
            ),
        ),
    ]
