# Generated by Django 4.2 on 2023-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0002_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrowing",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
