# Generated by Django 4.2 on 2023-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0005_alter_borrowing_borrow_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
