# Generated by Django 4.2 on 2023-04-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0012_alter_borrowing_borrow_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(),
        ),
    ]
