# Generated by Django 4.2 on 2023-04-25 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0013_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(default=datetime.date(2023, 5, 5)),
        ),
    ]
