# Generated by Django 4.2 on 2023-04-25 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0014_alter_borrowing_expected_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 5)),
        ),
    ]
