# Generated by Django 4.2 on 2023-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0015_alter_borrowing_expected_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(),
        ),
    ]
