# Generated by Django 4.2 on 2023-04-26 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0016_alter_borrowing_expected_return_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrowing",
            unique_together=set(),
        ),
    ]
