# Generated by Django 4.2 on 2023-05-07 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0017_alter_borrowing_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="books",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="users",
            new_name="user",
        ),
    ]
